experiment_name: sepal-ppi-feature-contant
defaults:
- _self_
- training: default_nolr
- model: nonefeature
- data: Strings_plant50_bf16/esm2_15binput1280
- logging: default
- output: default
- inference: default
change_embedding_dim: 1280

