mode: inference
model:
  model_path: results/Strings_plant50/esm2_15b/sepal-ppi-projector-feature-contant/last_model.pth
  pooling_type: avg
  interaction_type: hadamard
  classifier_type: standard
  embedding_dim: 1280
inference:
  batch_size: 32
  threshold: 0.5
  best_epoch: 10
data:
  use_sequence_data: true
  embedding_file: emb/Strings_plant50/esm2_15b.Strings_plant50.avg.1280.lmdb/noCLSeos.lmdb/bucketed_embeddings.lmdb
  embedding_dim: 1280
  target_precision: bf16
  train_file: dataset/Strings_plant50/c1Train.txt
  validation_file: dataset/Strings_plant50/c2Test.txt
  test_file: dataset/Strings_plant50/c3Test.txt
  fasta_file: dataset/Strings_plant50/protein.fasta
  cache_size: 15000
  max_length: 1000
  cis_type: false
  test_files:
    c2: dataset/Strings_plant50/c2Test.txt
    c3: dataset/Strings_plant50/c3Test.txt
output:
  generate_confusion_matrix: true
  save_predictions: true
  output_dir: results/Strings_plant50/esm2_15b/sepal-ppi-projector-feature-contant
