ensemble_config: results/Human/esm2_15b/cis_residue_ensemble/ensemble_inference_config.yaml

test_id_file: predict/Human/c3Test.csv
test_protein_fasta: predict/Human/protein.fasta

test_protein_lmdb_dir: 
  model1: predict/Human/HumanC3/esm2_15b.HumanC3.avg.1280.lmdb/onlyCLS.lmdb
  model2:  predict/Human/HumanC3/esm2_15b.HumanC3.avg.1280.lmdb/noCLSeos.lmdb/bucketed_embeddings.lmdb


model1: 
  cis_only: True
  cis_Interpretability: false
  Interpretability_lmdb_dir: emb/Human/esm2_15b.Human.lmdb/onlyCLS.lmdb
  Interpretability_protein_id: dataset/Human/2193/c1Train.txt
  top_k: 10
model2: 
  #残基级别推理
  Residue_Interpretability: True