configs:
- results/Strings_plant50_bf16/esm2_15b/sepal-ppi-cis/best_config.yaml
- results/Strings_plant50_bf16/ab-nosst-/esm2_15b/sepal-ppi-projector-feature-contant/best_config.yaml
mode: logits
debug: false
train_model: weighted
