experiment_name: sepal-ppi-feature-contant
defaults:
- _self_
- training: default_nolr
- model: projector-feature-contant
- data: Human/esm2_15binput1280
- logging: default
- output: default
- inference: default
change_embedding_dim: 1280
protein_fasta_path: dataset/Human/2193/protein.fasta
all_feature_folder: mutifeature/Human
