configs:
- results/Interact_Ara/esm2_15b/sepal-ppi-cis/best_config.yaml
- results/Interact_Ara/ab-nosst-/esm2_15b/sepal-ppi-projector-feature-contant/best_config.yaml
mode: logits
debug: false
train_model: weighted
