experiment_name: fusion-finetune
description: fusion_finetune_avg_to_1280
defaults:
- _self_
- training: low
- logging: default
- output: default
- inference: default
- data: Strings_plant50_int8/esm2_15b.avg
- model: avg_pooling-change
finetune:
  base_checkpoint: results/Strings_plant50_int8/esm2_15b/sepal-ppi-avg-noinput/best_model.pth
  use_pretrained_embedding_dim: false
  freeze_except:
  - input_layer
  - classifier
change_embedding_dim: 1280
protein_fasta_path: dataset/Strings_plant50/protein.fasta
all_feature_folder: mutifeature/Strings_plant50
