ensemble_config: results/Strings_plant50/esm2_15b/ensemble-st50_cis_nonefeature/ensemble_inference_config.yaml

test_id_file: predict/Gmax/Gly/hh50.csv
test_protein_fasta: predict/Gmax/Gly/subset.fasta

test_protein_lmdb_dir: 

  model1: predict/Gmax/Gly/esm2_15b.Gly.diff.avg.1280.lmdb/noCLSeos.lmdb/bucketed_embeddings.lmdb
  model2: predict/Gmax/Gly/esm2_15b.Gly.diff.avg.1280.lmdb/onlyCLS.lmdb




model1: 
  #残基级别推理
  Residue_Interpretability: True
model2: 
  cis_only: True
  cis_Interpretability: false
  Interpretability_lmdb_dir: emb/Strings_plant50/esm2_15b.Strings_plant50.lmdb/onlyCLS.lmdb
  Interpretability_protein_id: dataset/Strings_plant50/c1Train.txt
  top_k: 10